export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const EVENTS_ROUTE = '/events'
export const CALENDAR_ROUTE = '/calendar'
export const ABOUT_ROUTE = '/about'
export const EVENT_ROUTE = '/event'